services:
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - react-static:/usr/share/nginx/html
    depends_on:
      - symfony
      - react
    
  symfony:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    depends_on:
      - db
  
  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - react-static:/app/dist
    depends_on:
      - symfony

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  
volumes:
  mysqldata:
  react-static: